# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - binaries/hugo --baseURL="http://hugo-ci-s3-ec2.s3-website-us-west-1.amazonaws.com/"

# Deploy
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "hugo-ci-s3-ec2"
  skip_cleanup: true
  local_dir: public  
